/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DossiesRouteImport } from './routes/dossies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as TriagensRouteImport } from './routes/triagens'
import { Route as AtendimentoIdRouteImport } from './routes/atendimento.$id'
import { Route as ConfiguracoesPerfilRouteImport } from './routes/configuracoes_.perfil'
import { Route as TIdRouteImport } from './routes/t.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiesRoute = DossiesRouteImport.update({
  id: '/dossies',
  path: '/dossies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TriagensRoute = TriagensRouteImport.update({
  id: '/triagens',
  path: '/triagens',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoIdRoute = AtendimentoIdRouteImport.update({
  id: '/atendimento/$id',
  path: '/atendimento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesPerfilRoute = ConfiguracoesPerfilRouteImport.update({
  id: '/configuracoes_/perfil',
  path: '/configuracoes/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const TIdRoute = TIdRouteImport.update({
  id: '/t/$id',
  path: '/t/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dossies': typeof DossiesRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRoute
  '/planos': typeof PlanosRoute
  '/relatorios': typeof RelatoriosRoute
  '/setup': typeof SetupRoute
  '/triagens': typeof TriagensRoute
  '/atendimento/$id': typeof AtendimentoIdRoute
  '/configuracoes/perfil': typeof ConfiguracoesPerfilRoute
  '/t/$id': typeof TIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dossies': typeof DossiesRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRoute
  '/planos': typeof PlanosRoute
  '/relatorios': typeof RelatoriosRoute
  '/setup': typeof SetupRoute
  '/triagens': typeof TriagensRoute
  '/atendimento/$id': typeof AtendimentoIdRoute
  '/configuracoes/perfil': typeof ConfiguracoesPerfilRoute
  '/t/$id': typeof TIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dossies': typeof DossiesRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRoute
  '/planos': typeof PlanosRoute
  '/relatorios': typeof RelatoriosRoute
  '/setup': typeof SetupRoute
  '/triagens': typeof TriagensRoute
  '/atendimento/$id': typeof AtendimentoIdRoute
  '/configuracoes_/perfil': typeof ConfiguracoesPerfilRoute
  '/t/$id': typeof TIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/dossies'
    | '/login'
    | '/pacientes'
    | '/planos'
    | '/relatorios'
    | '/setup'
    | '/triagens'
    | '/atendimento/$id'
    | '/configuracoes/perfil'
    | '/t/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/dossies'
    | '/login'
    | '/pacientes'
    | '/planos'
    | '/relatorios'
    | '/setup'
    | '/triagens'
    | '/atendimento/$id'
    | '/configuracoes/perfil'
    | '/t/$id'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/dossies'
    | '/login'
    | '/pacientes'
    | '/planos'
    | '/relatorios'
    | '/setup'
    | '/triagens'
    | '/atendimento/$id'
    | '/configuracoes_/perfil'
    | '/t/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DossiesRoute: typeof DossiesRoute
  LoginRoute: typeof LoginRoute
  PacientesRoute: typeof PacientesRoute
  PlanosRoute: typeof PlanosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SetupRoute: typeof SetupRoute
  TriagensRoute: typeof TriagensRoute
  AtendimentoIdRoute: typeof AtendimentoIdRoute
  ConfiguracoesPerfilRoute: typeof ConfiguracoesPerfilRoute
  TIdRoute: typeof TIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossies': {
      id: '/dossies'
      path: '/dossies'
      fullPath: '/dossies'
      preLoaderRoute: typeof DossiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triagens': {
      id: '/triagens'
      path: '/triagens'
      fullPath: '/triagens'
      preLoaderRoute: typeof TriagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento/$id': {
      id: '/atendimento/$id'
      path: '/atendimento/$id'
      fullPath: '/atendimento/$id'
      preLoaderRoute: typeof AtendimentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes_/perfil': {
      id: '/configuracoes_/perfil'
      path: '/configuracoes/perfil'
      fullPath: '/configuracoes/perfil'
      preLoaderRoute: typeof ConfiguracoesPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$id': {
      id: '/t/$id'
      path: '/t/$id'
      fullPath: '/t/$id'
      preLoaderRoute: typeof TIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DossiesRoute: DossiesRoute,
  LoginRoute: LoginRoute,
  PacientesRoute: PacientesRoute,
  PlanosRoute: PlanosRoute,
  RelatoriosRoute: RelatoriosRoute,
  SetupRoute: SetupRoute,
  TriagensRoute: TriagensRoute,
  AtendimentoIdRoute: AtendimentoIdRoute,
  ConfiguracoesPerfilRoute: ConfiguracoesPerfilRoute,
  TIdRoute: TIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
